apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.MYSQL.DEPLOYMENT.REPLICACOUNT }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  serviceName: mysql
  template:
    metadata:
      name: mysql
      labels:
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.MYSQL.DEPLOYMENT.IMAGE }}:{{ .Values.MYSQL.DEPLOYMENT.TAG }}
        env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: MYSQL_INITDB_SKIP_TZINFO
            value: "yes"
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.MYSQL.MYSQL_ROOT_PASWORD }}
          - name: MYSQL_DATABASE
            value: "nacos"
          - name: MYSQL_USER
            value: "nacos"
          - name: MYSQL_PASSWORD
            value: "nacos"
        resources:
          limits:
            cpu: 400m
            memory: 2048Mi
          requests:
            cpu: 300m
            memory: 1024Mi
        ports:
          - containerPort: 3306
            name: mysql

        volumeMounts:
          - name: mysql-cnf
            mountPath: /etc/my.cnf.d
          - name: mysql-user
            mountPath: /etc/foo
            readOnly: true
      volumes:
        - name: mysql-cnf
          configMap:
            name: mysql-config
            items:
            - key: my.cnf
              path: my.cnf
        - name: mysql-user
          secret:
            secretName: mysql-user
      serviceAccount: mysql-role
