apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}
spec:
  type: {{ .Values.MYSQL.SERVICE.TYPE }}
  ports:
  - port: {{ .Values.MYSQL.SERVICE.PORT }}
    name: mysql
  selector:
    {{- include "mysql.labels" . | nindent 4 }}
  clusterIP: None
